version: "3.9"
services:
    frontend:
        image: tbj/webapp
        build:
            context: .
            dockerfile: frontend.Dockerfile
        ports:
            - "3000:3000"
        volumes:
            - ./frontend/src:/app/src
            - /app/node_modules

    backend:
        image: tbj/api
        build:
            context: . 
            dockerfile: backend.Dockerfile
        ports:
            - "8000:8000"
        volumes:
            - ./backend:/code
        command: python manage.py runserver 0.0.0.0:8000